#!/bin/sh

cat <<EOF > /etc/firewall.6doll
ip6tables -t nat -I POSTROUTING -s fc00::/7 ! -d fc00::/7 -j MASQUERADE
EOF

uci -q batch <<-EOF
	set system.@system[0].hostname='6doll'
	commit system
	set network.lan.proto='dhcp'
	set network.lan.ipaddr=''
	set network.lan.netmask=''
	commit network
	add firewall include
	set firewall.@include[-1].path='/etc/firewall.6doll'
	commit firewall
	set dhcp.lan.ra='server'
	set dhcp.lan.ra_default='2'
	set dhcp.lan.ra_slaac='1'
	set dhcp.lan.ra_flags='none'
	set dhcp.lan.ra_preference='low'
	set dhcp.lan.ra_maxinterval='60'
	set dhcp.lan.ra_mininterval='15'
	set dhcp.lan.ra_lifetime='300'
	set dhcp.lan.ra_useleasetime='1'
	set dhcp.lan.leasetime='600'
	commit dhcp
EOF
