#!/bin/sh

cat <<EOF > /etc/firewall.6doll
ip6tables -t filter -I forwarding_lan_rule -s fc00::/7 ! -d fc00::/7 -j ACCEPT
ip6tables -t nat -I POSTROUTING -s fc00::/7 ! -d fc00::/7 -j MASQUERADE
EOF

uci -q batch <<-EOF
	set system.@system[0].hostname='6doll'
	set system.led_white='led'
	set system.led_white.name='Link'
	set system.led_white.sysfs='microuter-n300:white:wlan'
	set system.led_white.trigger='switch0'
	set system.led_white.port_mask=0x1
	commit system
	set network.lan.proto='dhcp'
	set network.lan.ipaddr=''
	set network.lan.netmask=''
	set network.lanx='interface'
	set network.lanx.ifname='@lan'
	set network.lanx.proto='static'
	set network.lanx.ipaddr='192.168.8.1'
	set network.lanx.netmask='255.255.255.0'
	commit network
	add firewall include
	set firewall.@include[-1].path='/etc/firewall.6doll'
	commit firewall
	set dhcp.lan.ra='server'
	set dhcp.lan.ra_default='2'
	set dhcp.lan.ra_slaac='1'
	set dhcp.lan.ra_flags='none'
	set dhcp.lan.ra_dns='0'
	set dhcp.lan.ra_preference='low'
	set dhcp.lan.ra_maxinterval='60'
	set dhcp.lan.ra_mininterval='15'
	set dhcp.lan.ra_lifetime='300'
	set dhcp.lan.ra_useleasetime='1'
	set dhcp.lan.leasetime='600'
	commit dhcp
EOF

# Use serial number (printed on case) as password
PASSWD=$(dd if=/dev/mtd2 bs=1 skip=16432 count=16)
echo -e "${PASSWD}\n${PASSWD}" | passwd
